apiVersion: v1
kind: Service
metadata:
  name: bnpl-config-service
  labels:
    app: bnpl-config-service
spec:
  type: ClusterIP
  selector:
    app: bnpl-catalog-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
